version: '3.4'
services:

  creature_keeper:
    image: localhost:5000/personal/creature-keeper:dev
    networks:
      - creature
    ports:
      - 8080:8080
    environment:
      DATABASE_CREATURE_KEEPER_URL: jdbc:mariadb://maria:3306/creature_keeper_db

networks:
  creature:
    external:
      name: creature