version: '3.4'
services:

  creature_keeper:
    image: localhost:5000/personal/creature-keeper:dev
    networks:
      - creature
    ports:
      - 8090:8090
    environment:
      DATABASE_CREATURE_KEEPER_HOST: maria

networks:
  creature:
    external:
      name: creature